# Databricks notebook source
# MAGIC %md
# MAGIC Connect to Bronze

# COMMAND ----------

from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import *
from delta.tables import *
import pandas as pd
import os

# COMMAND ----------

try:
    dbutils.notebook.run('/Workspace/Users/rajeswarivaddi@dataengineer668.onmicrosoft.com/mount_bsg',0)
except Exception as e:
    print(e)

# COMMAND ----------

# MAGIC %md
# MAGIC JSON to Parquet

# COMMAND ----------

def json_to_parquet():
    
    for file in files_info:
       
        try:
            if os.path.exists("/dbfs/mnt/sourcedata/"+ file.name):
                spark.read.option("multiline", "true").json("dbfs:/mnt/sourcedata/"+file.name).toPandas().to_parquet("/dbfs/mnt/bronze/"+ file.name.replace('.json','.parquet'))
                dbutils.fs.mv("dbfs:/mnt/sourcedata/"+file.name, "dbfs:/mnt/archive/")                
            else:
                print(FileNotFoundError)
        except Exception as e:
            print(e)
            dbutils.fs.mv("dbfs:/mnt/sourcedata/"+file.name, "dbfs:/mnt/error/")
        

files_info = dbutils.fs.ls("dbfs:/mnt/sourcedata")
json_to_parquet()


# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS file1 (
# MAGIC id BIGINT GENERATED BY DEFAULT AS IDENTITY
# MAGIC )
# MAGIC USING DELTA

# COMMAND ----------


def create_df(bpath):
    file_details = [(file.name.split('.')[0],file.modificationTime)]
    file_details_df = spark.createDataFrame(file_details, ["file_name", "timestamp"])
    file_details_df = file_details_df.withColumn("date", to_date(from_unixtime(col("timestamp") / 1000))).withColumn("timestamp",from_unixtime(col("timestamp") / 1000).cast("timestamp"))
    display(file_details_df)
    return file_details_df
    

files_info = dbutils.fs.ls("dbfs:/mnt/bronze")


for file in files_info:
    file=create_df("/dbfs/mnt/bronze/"+ file.name)
    file.write.format('delta').option("mergeSchema", "true").mode("append").saveAsTable('file1')


# COMMAND ----------

# MAGIC %sql
# MAGIC select* from file1;
# MAGIC
# MAGIC
# MAGIC --SELECT * FROM DELTA.`/dbfs/mnt/delta/file1`;
# MAGIC
# MAGIC --DELETE FROM delta. `/dbfs/mnt/delta/file1`;
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC Modifications --> 
# MAGIC                 
